# Generated by Django 3.2.9 on 2022-03-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220319_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='fav_animal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='fav_drink',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='radio', max_length=20),
            preserve_default=False,
        ),
    ]
