# Generated by Django 3.2.9 on 2022-04-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
