# Generated by Django 3.2.9 on 2022-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_choice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='fav_animal',
            new_name='spirit_animal',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='guest',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='guest',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
